/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Bridge */

#ifndef _Included_Bridge
#define _Included_Bridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Bridge
 * Method:    cppNextPrime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Bridge_cppNextPrime
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
